// <auto-generated />
using System;
using LaLigaFans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaLigaFans.Infrastructure.Migrations
{
    [DbContext(typeof(LaLigaFansDbContext))]
    [Migration("20240415164407_AddColumnIsActiveForSoftDeleteOnTablesTeamPlayerNewsAndProduct")]
    partial class AddColumnIsActiveForSoftDeleteOnTablesTeamPlayerNewsAndProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Address identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Address city");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Payment order identifier");

                    b.Property<string>("StreetEtc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Address street etc");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasComment("Address is a entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Application user first name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Application user last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("ApplicationUser is a entity class that extends IdentityUser");

                    b.HasData(
                        new
                        {
                            Id = "1dcd54f5-dc66-4540-8cf9-d44658029bfd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4aa9a9fb-b679-4c1a-9d76-43ffba897965",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGr4tIOMpmVaUrN9Nhyea/jT/zGLp86O9L2AkJb51CZH7X+YvYJQpnyiEwaW1ZNutQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1343a428-3604-437f-bb19-e2e3c3813f93",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a929bb03-dca8-4047-b1d5-b685e72dc657",
                            Email = "publisher@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Publisher",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "PUBLISHER@GMAIL.COM",
                            NormalizedUserName = "PUBLISHER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIS/QHEdgwRW/qnvacYkNu7H19AdmTNLLztIhtel9IMQxCtl6WgwMc6XV8wmI/q1HQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69f890a4-83da-4ef8-b9e5-0008a739023a",
                            TwoFactorEnabled = false,
                            UserName = "publisher@gmail.com"
                        },
                        new
                        {
                            Id = "9ec8c321-e4d2-4ec4-854c-81b04f6b53c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49de1459-ca08-4752-8ef5-f5cc061efcfd",
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "User",
                            LastName = "Userov",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "USER1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEONTVmXa9+SSEAJ9T7reroSGlrvOtAo6CHLaeshQPwOogrQh8KqktcAPlPH7fjt7gQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f95278f-bd99-456a-b710-10e5afacfd1f",
                            TwoFactorEnabled = false,
                            UserName = "user1@gmail.com"
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUserProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("ApplicationUser identifier");

                    b.HasKey("ProductId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ApplicationUsersProducts");

                    b.HasComment("ApplicationUserProduct is a mapping table entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUserTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Team identifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("ApplicationUser identifier");

                    b.HasKey("TeamId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ApplicationUsersTeams");

                    b.HasComment("ApplicationUserTeam is a mapping table entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Cart identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Cart applicaion user identifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasComment("Cart is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "1dcd54f5-dc66-4540-8cf9-d44658029bfd"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "176d92cc-bdaf-4569-94b8-fa377f980d89"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "9ec8c321-e4d2-4ec4-854c-81b04f6b53c6"
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.CartProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasComment("Cart identifier");

                    b.HasKey("ProductId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartsProducts");

                    b.HasComment("CartProduct is a mapping table entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Category name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasComment("Category is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Scarf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cup"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bag"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Keychain"
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Comment identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Comment author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Comment content");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Comment creation date");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int")
                        .HasComment("Comment news identifier");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Comment product identifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Comment title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("NewsId");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");

                    b.HasComment("Comment is a entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("News identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("News content");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("News image URL");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("News is active or not active(soft deleted)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("News owner identifier");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2")
                        .HasComment("News published date");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Identifier of team the news is about");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("News title");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TeamId");

                    b.ToTable("News");

                    b.HasComment("News is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "The Barcelona team won 3:2 away from Paris Saint-Germain in the first 1/4-final match of the Champions League.\r\nRafinha gave the Catalans the lead in the 37th minute, but early in the second half PSG made a quick turnaround through Ousmane Dembele in the 48th minute and Vitinha in the 51st minute. After that, however, the Catalans took the initiative again and in the 62nd minute the tie was restored with Rafinha's second goal. In the end, the final result was shaped by Andreas Christensen's goal in the 77th minute, which brought victory to Barca.\r\nThe second match between the two teams will be on April 16th in Spain, where we can expect another very interesting match.",
                            ImageURL = "BarcaNews1.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2024, 4, 15, 19, 44, 7, 273, DateTimeKind.Local).AddTicks(4833),
                            TeamId = 1,
                            Title = "Barcelona crushed PSG and took the lead ahead of the second leg"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The Barcelona team could not beat the Athletic Bilbao team and the match ended 0:0, with which the Catalans lost 2 more points in the standings and are now 8 points away from the first in the standings.\r\nThere are only 5 rounds left in the championship and Barcelona's chances of catching up to first place are already minimal.\r\nFor the Catalans, it remains to fight for a trophy in the Champions League, where they will face a quarter-final match against a team from Paris Saint-Germain, and for the Copa del Rey in Spain, where they will play against a Sevilla team in the semi-finals.",
                            ImageURL = "BarcaNews2.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2023, 12, 30, 19, 44, 7, 273, DateTimeKind.Local).AddTicks(4838),
                            TeamId = 1,
                            Title = "Barcelona with new lost points in La Liga"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Real Madrid and Manchester City had a very spectacular and interesting match in their first leg of the quarter-finals of the Champions League, which ended in a 3-3 draw.\r\nAt the very beginning of the match, Manchester City took the lead with a goal by Bernardo Silva in the 2nd minute, but then Real Madrid scored two goals, the first of which was an own goal by Ruben Diaz in the 12th minute, and the second goal was by Rodrigo Goes in the 14th minute. However, City then turned the score around again with goals from Phil Foden in the 66th minute and Josko Guardiol in the 71st minute. And finally Federico Valverde scored for Real and that's how the final score was 3:3.\r\nThe second match between the two teams will be on April 17.",
                            ImageURL = "RealNews1.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2024, 3, 19, 19, 44, 7, 273, DateTimeKind.Local).AddTicks(4840),
                            TeamId = 2,
                            Title = "Real Madrid and Manchester City could not beat each other"
                        },
                        new
                        {
                            Id = 4,
                            Content = "The Real Madrid team convincingly defeated the Osasuna team with 4:0 and now leads the La Liga standings ahead of the second by 8 points.\r\nOnly 4 rounds remain until the end of the championship and Real are already very close to the title this season.\r\nIn addition to La Liga, Real also have matches in the quarter-finals of the Champions League against the Manchester City team, as well as the semi-final of the King's Cup in Spain against the Valencia team.\r\nIf Real manage to win all three they will complete a treble this season, which they haven't done in a long time.",
                            ImageURL = "RealNews2.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2024, 2, 15, 19, 44, 7, 273, DateTimeKind.Local).AddTicks(4842),
                            TeamId = 2,
                            Title = "Real Madrid with another victory in La Liga"
                        },
                        new
                        {
                            Id = 5,
                            Content = "The Atletico Madrid team managed to beat Borussia Dortmund in a very close match in the first round of the quarter-finals of the Champions League.\r\nAtlético took the lead early in the match with a goal from Rodrigo De Paul in the 4th minute, then they made it 2-0 with a goal from Samuel Lino in the 32nd minute. Finally, Dortmund pulled one back with a goal from Sebastien Alle in the 81st minute and the match ended 2:1 for the Atlético team.\r\nThe second match between the two teams will be on April 16th, and we expect a very even game from both teams again.",
                            ImageURL = "AtleticoNews.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2023, 9, 15, 19, 44, 7, 273, DateTimeKind.Local).AddTicks(4844),
                            TeamId = 3,
                            Title = "Atletico Madrid with a tough win against Borussia Dortmund"
                        },
                        new
                        {
                            Id = 6,
                            Content = "The Sevilla team achieved a hard-fought victory in La Liga against the Getafe team, but with this victory, the Sevilla team managed to move away from the relegation group that they were very close to before this match.\r\nThe only goal in the match was scored by Sergio Ramost, with which the Sevilla team won with a score of 0:1.\r\nUntil the end of the championship, the Sevilla team has 6 more games left in which they must manage to win points to stay above the relegation group.\r\nSevilla's next game is against Las Palmas on April 14th.",
                            ImageURL = "SevillaNews.png",
                            IsActive = false,
                            OwnerId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            PublishedOn = new DateTime(2024, 4, 15, 12, 44, 7, 273, DateTimeKind.Local).AddTicks(4846),
                            TeamId = 5,
                            Title = "Sevilla with a difficult but important victory"
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Order buyer identifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Order");

                    b.HasComment("Order is a entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Payment identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Payment order identifier");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasComment("Payment method");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Payment total price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasComment("Payment is a entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Player identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Player age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Player first name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Player is active or not active(soft deleted)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Player last name");

                    b.Property<string>("PlayerImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Player image URL");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Player team id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasComment("Player is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            FirstName = "Marc-Andre",
                            IsActive = false,
                            LastName = "ter Stegen",
                            PlayerImageUrl = "TerStegen.png",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            FirstName = "Frenkie",
                            IsActive = false,
                            LastName = "de Jong",
                            PlayerImageUrl = "Frenki.png",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            FirstName = "Joao",
                            IsActive = false,
                            LastName = "Cancelo",
                            PlayerImageUrl = "Cancelo.png",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 35,
                            FirstName = "Robert",
                            IsActive = false,
                            LastName = "Lewandowski",
                            PlayerImageUrl = "Lewandowski.png",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Age = 24,
                            FirstName = "Joao",
                            IsActive = false,
                            LastName = "Felix",
                            PlayerImageUrl = "Felix.png",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            Age = 31,
                            FirstName = "Thibaut",
                            IsActive = false,
                            LastName = "Courtois",
                            PlayerImageUrl = "Courtois.png",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Age = 32,
                            FirstName = "Lucas",
                            IsActive = false,
                            LastName = "Vazquez",
                            PlayerImageUrl = "Vazquez.png",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            Age = 32,
                            FirstName = "Dani",
                            IsActive = false,
                            LastName = "Carvajal",
                            PlayerImageUrl = "Carvajal.png",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            Age = 23,
                            FirstName = "Vinicius",
                            IsActive = false,
                            LastName = "Junior",
                            PlayerImageUrl = "ViniJR.png",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            Age = 31,
                            FirstName = "Jan",
                            IsActive = false,
                            LastName = "Oblak",
                            PlayerImageUrl = "Oblak.png",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 11,
                            Age = 35,
                            FirstName = "Axel",
                            IsActive = false,
                            LastName = "Witsel",
                            PlayerImageUrl = "Witsel.png",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            Age = 28,
                            FirstName = "Jose",
                            IsActive = false,
                            LastName = "Gaya",
                            PlayerImageUrl = "Gaya.png",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 13,
                            Age = 32,
                            FirstName = "Nemanja",
                            IsActive = false,
                            LastName = "Gudelj",
                            PlayerImageUrl = "Gudelj.png",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 14,
                            Age = 23,
                            FirstName = "Eric",
                            IsActive = false,
                            LastName = "Garcia",
                            PlayerImageUrl = "Garcia.png",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 15,
                            Age = 26,
                            FirstName = "Ander",
                            IsActive = false,
                            LastName = "Guevara",
                            PlayerImageUrl = "Guevara.png",
                            TeamId = 7
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Product identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Product category identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Product description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Product image URL");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Product is active or not active(soft deleted)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Product name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product price");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Product team identifier");

                    b.Property<int>("UnitsAvailable")
                        .HasColumnType("int")
                        .HasComment("Product available units");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeamId");

                    b.ToTable("Products");

                    b.HasComment("Product is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Original Barcelona t-shirt made of 100% breathable fabric.",
                            ImageURL = "BarcaTShirt.png",
                            IsActive = false,
                            Name = "Barcelona T-Shirt",
                            Price = 34.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Original Barcelona scarf made of cotton and synthetic fabric.",
                            ImageURL = "BarcaScarf.png",
                            IsActive = false,
                            Name = "Barcelona Scarf",
                            Price = 22.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Original Barcelona size 5 ball made of synthetic materials.",
                            ImageURL = "BarcaBall.png",
                            IsActive = false,
                            Name = "Barcelona Ball",
                            Price = 29.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Original Barcelona tea cup made of porcelain.",
                            ImageURL = "BarcaCup.png",
                            IsActive = false,
                            Name = "Barcelona Cup",
                            Price = 17.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Original Barcelona bag made of synthetic waterproof material.",
                            ImageURL = "BarcaBag.png",
                            IsActive = false,
                            Name = "Barcelona Bag",
                            Price = 24.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Original Barcelona keychain made of stainless steel.",
                            ImageURL = "BarcaKeychain.png",
                            IsActive = false,
                            Name = "Barcelona Keychain",
                            Price = 12.99m,
                            TeamId = 1,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Original Real Madrid t-shirt made of 100% breathable fabric.",
                            ImageURL = "RealTShirt.png",
                            IsActive = false,
                            Name = "Real Madrid T-Shirt",
                            Price = 34.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Original Real Madrid scarf made of cotton and synthetic fabric.",
                            ImageURL = "RealScarf.png",
                            IsActive = false,
                            Name = "Real Madrid Scarf",
                            Price = 22.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Original Real Madrid size 5 ball made of synthetic materials.",
                            ImageURL = "RealBall.png",
                            IsActive = false,
                            Name = "Real Madrid Ball",
                            Price = 29.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Original Real Madrid tea cup made of porcelain.",
                            ImageURL = "RealCup.png",
                            IsActive = false,
                            Name = "Real Madrid Cup",
                            Price = 17.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Original Real Madrid bag made of synthetic waterproof material.",
                            ImageURL = "RealBag.png",
                            IsActive = false,
                            Name = "Real Madrid Bag",
                            Price = 24.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Original Real Madrid keychain made of stainless steel.",
                            ImageURL = "RealKeychain.png",
                            IsActive = false,
                            Name = "Real Madrid Keychain",
                            Price = 12.99m,
                            TeamId = 2,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Original Atletico Madrid t-shirt made of 100% breathable fabric.",
                            ImageURL = "AtleticoTShirt.png",
                            IsActive = false,
                            Name = "Atletico Madrid T-Shirt",
                            Price = 30.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Original Atletico Madrid scarf made of cotton and synthetic fabric.",
                            ImageURL = "AtleticoScarf.png",
                            IsActive = false,
                            Name = "Atletico Madrid Scarf",
                            Price = 19.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Original Atletico Madrid size 5 ball made of synthetic materials.",
                            ImageURL = "AtleticoBall.png",
                            IsActive = false,
                            Name = "Atletico Ball",
                            Price = 25.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Original Atletico Madrid tea cup made of porcelain.",
                            ImageURL = "AtleticoCup.png",
                            IsActive = false,
                            Name = "Atletico Madrid Cup",
                            Price = 14.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Original Atletico Madrid bag made of synthetic waterproof material.",
                            ImageURL = "AtleticoBag.png",
                            IsActive = false,
                            Name = "Atletico Madrid Bag",
                            Price = 21.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "Original Atletico Madrid keychain made of stainless steel.",
                            ImageURL = "AtleticoKeychain.png",
                            IsActive = false,
                            Name = "Atletico Madrid Keychain",
                            Price = 10.99m,
                            TeamId = 3,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Original Valencia t-shirt made of 100% breathable fabric.",
                            ImageURL = "ValenciaTShirt.png",
                            IsActive = false,
                            Name = "Valencia T-Shirt",
                            Price = 24.99m,
                            TeamId = 4,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Original Valencia scarf made of cotton and synthetic fabric.",
                            ImageURL = "ValenciaScarf.png",
                            IsActive = false,
                            Name = "Valencia Scarf",
                            Price = 16.99m,
                            TeamId = 4,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Original Sevilla t-shirt made of 100% breathable fabric.",
                            ImageURL = "SevillaTShirt.png",
                            IsActive = false,
                            Name = "Sevilla T-Shirt",
                            Price = 22.49m,
                            TeamId = 5,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Original Sevilla size 5 ball made of synthetic materials.",
                            ImageURL = "SevillaBall.png",
                            IsActive = false,
                            Name = "Sevilla Ball",
                            Price = 20.99m,
                            TeamId = 5,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Original Girona t-shirt made of 100% breathable fabric.",
                            ImageURL = "GironaTShirt.png",
                            IsActive = false,
                            Name = "Girona T-Shirt",
                            Price = 19.99m,
                            TeamId = 6,
                            UnitsAvailable = 10
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Original Alaves t-shirt made of 100% breathable fabric.",
                            ImageURL = "AlavesTShirt.png",
                            IsActive = false,
                            Name = "Alaves T-Shirt",
                            Price = 19.99m,
                            TeamId = 7,
                            UnitsAvailable = 10
                        });
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Question identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Question author identifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Question content");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Question created on date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Question title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Questions");

                    b.HasComment("Question is a entity class");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Team identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Team coach name");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int")
                        .HasComment("Team founded year");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Team information");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Team is active or not active(soft deleted)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Team logo URL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Team name");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasComment("Team is a entity class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachName = "Xavi Hernandez",
                            FoundedYear = 1899,
                            Information = "Barcelona football club is one of the top teams in the Spanish football league. It was founded on November 29, 1899. The team's stadium is called \"Camp Nou\" and has a capacity of 105 thousand seats. The Barcelona team has won the Champions League five times, the FIFA Club World Cup three times, the Spanish Championship twenty-seven times, the Copa del Rey thirty-one times, the Spanish Super Cup fourteen times and many more.",
                            IsActive = false,
                            LogoUrl = "BarcelonaLogo.png",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            CoachName = "Carlo Ancelotti",
                            FoundedYear = 1902,
                            Information = "Real Madrid football club is one of the top teams in the Spanish football league. It was founded on March 6, 1902. The team's stadium is called \"Santiago Bernabeu\" and has a capacity of 83 thousand seats. The Real Madrid team has won the Champions League eight times, the FIFA Club World Cup eight times, the Spanish Championship thirty-five times, the Copa del Rey twenty times, the Spanish Super Cup thirteen times and many more.",
                            IsActive = false,
                            LogoUrl = "RealMadridLogo.png",
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            CoachName = "Diego Simeone",
                            FoundedYear = 1903,
                            Information = "Atletico Madrid football club is one of the top teams in the Spanish football league. It was founded on April 26, 1903. The team's stadium is called \"Metropolitano\" and has a capacity of 70 thousand seats. The Atlético Madrid team has won three times the Europa League, eleven times the Spanish Championship, ten times the Copa del Rey, two times the Spanish Super Cup and others.",
                            IsActive = false,
                            LogoUrl = "AtleticoMadridLogo.png",
                            Name = "Atletico Madrid"
                        },
                        new
                        {
                            Id = 4,
                            CoachName = "Ruben Baraja",
                            FoundedYear = 1919,
                            Information = "Valencia football club is one of the teams in the Spanish football league. It was founded on March 18, 1919. The team's stadium is called \"Camp de Mestalla\" and has a capacity of 50 thousand seats. The Valencia team has won the Spanish Championship six times, the Copa del Rey eight times, the Spanish Super Cup once and others.",
                            IsActive = false,
                            LogoUrl = "ValenciaLogo.png",
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 5,
                            CoachName = "Quiwue Sanchez",
                            FoundedYear = 1890,
                            Information = "Sevilla football club is one of the teams in the Spanish football league. It was founded on January 25, 1890. The team's stadium is called \"Ramon Sanchez Pizjuan\" and has a capacity of 43 thousand seats. The Sevilla team has won the Europa League five times, the Spanish Championship once, the Copa del Rey five times, the Spanish Super Cup once and others.",
                            IsActive = false,
                            LogoUrl = "SevillaLogo.png",
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 6,
                            CoachName = "Michel Sanchez",
                            FoundedYear = 1930,
                            Information = "Girona football club is one of the teams in the Spanish football league. It was founded on July 23, 1930. The team's stadium is called \"Municipal de Montilivi\" and has a capacity of 15 thousand seats. The team of Girona has won the second Spanish Championship once, the third Spanish Championship five times, the Super Cup of Catalonia once and others.",
                            IsActive = false,
                            LogoUrl = "GironaLogo.png",
                            Name = "Girona"
                        },
                        new
                        {
                            Id = 7,
                            CoachName = "Luis Garcia",
                            FoundedYear = 1921,
                            Information = "Alaves football club is one of the teams in the Spanish football league. It was founded on January 23, 1921. The team's stadium is called \"Mendizorroza\" and has a capacity of 20 thousand seats. The Alaves team has won the second Spanish championship four times, the third Spanish championship twice, the Copa del Rey once and others.",
                            IsActive = false,
                            LogoUrl = "AlavesLogo.png",
                            Name = "Alaves"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "18c72cdd-60c4-4a26-b931-d183cb23e593",
                            ConcurrencyStamp = "e3139c5c-c171-4b0c-84be-30296b093191",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "91accf42-f5d3-47ee-8300-4671d5b47e46",
                            ConcurrencyStamp = "4411a386-ac55-4c0b-bc27-6d0e5a4714f0",
                            Name = "Publisher",
                            NormalizedName = "PUBLISHER"
                        },
                        new
                        {
                            Id = "f9725b78-b6af-40c1-90d4-f77de178c1fd",
                            ConcurrencyStamp = "c91b579c-ffcf-44fa-9cb3-efee89114504",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "user:fullname",
                            ClaimValue = "Admin Adminov",
                            UserId = "1dcd54f5-dc66-4540-8cf9-d44658029bfd"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "user:fullname",
                            ClaimValue = "Publisher Ivanov",
                            UserId = "176d92cc-bdaf-4569-94b8-fa377f980d89"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "user:fullname",
                            ClaimValue = "User Userov",
                            UserId = "9ec8c321-e4d2-4ec4-854c-81b04f6b53c6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1dcd54f5-dc66-4540-8cf9-d44658029bfd",
                            RoleId = "18c72cdd-60c4-4a26-b931-d183cb23e593"
                        },
                        new
                        {
                            UserId = "1dcd54f5-dc66-4540-8cf9-d44658029bfd",
                            RoleId = "f9725b78-b6af-40c1-90d4-f77de178c1fd"
                        },
                        new
                        {
                            UserId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            RoleId = "91accf42-f5d3-47ee-8300-4671d5b47e46"
                        },
                        new
                        {
                            UserId = "176d92cc-bdaf-4569-94b8-fa377f980d89",
                            RoleId = "f9725b78-b6af-40c1-90d4-f77de178c1fd"
                        },
                        new
                        {
                            UserId = "9ec8c321-e4d2-4ec4-854c-81b04f6b53c6",
                            RoleId = "f9725b78-b6af-40c1-90d4-f77de178c1fd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Address", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Order", "Order")
                        .WithOne("Address")
                        .HasForeignKey("LaLigaFans.Infrastructure.Data.Models.Address", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUserProduct", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("UsersFavorite")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUserTeam", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("FollowedTeams")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("Followers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Cart", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Cart")
                        .HasForeignKey("LaLigaFans.Infrastructure.Data.Models.Cart", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.CartProduct", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Cart", "Cart")
                        .WithMany("CartsProducts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("CartsProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Comment", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId");

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId");

                    b.Navigation("Author");

                    b.Navigation("News");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.News", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "Owner")
                        .WithMany("News")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("News")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Payment", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("LaLigaFans.Infrastructure.Data.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Player", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.Team", "Team")
                        .WithMany("Products")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Question", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("FavoriteProducts");

                    b.Navigation("FollowedTeams");

                    b.Navigation("News");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Cart", b =>
                {
                    b.Navigation("CartsProducts");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("CartsProducts");

                    b.Navigation("Comments");

                    b.Navigation("UsersFavorite");
                });

            modelBuilder.Entity("LaLigaFans.Infrastructure.Data.Models.Team", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("News");

                    b.Navigation("Players");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
